In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'Name': ['João', 'Maria', 'Pedro', 'Ana'], 'Age': [25, 30, 35, 20   ], 'City': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba']}
df = pd.DataFrame(data)
df

    Name  Age            City
0   João   25       São Paulo
1  Maria   30  Rio de Janeiro
2  Pedro   35  Belo Horizonte
3    Ana   20        Curitiba

In [3]:
df = pd.DataFrame(data, index = ['rank1', 'rank2', 'rank3', 'rank4'])
df

        Name  Age            City
rank1   João   25       São Paulo
rank2  Maria   30  Rio de Janeiro
rank3  Pedro   35  Belo Horizonte
rank4    Ana   20        Curitiba

In [4]:
data = [{'a': 1, 'b': 2}, {'a': 3, 'b': 4}, {'a': 5, 'b': 6}, {'a': 7, 'b': 8}]
df = pd.DataFrame(data)
df

   a  b
0  1  2
1  3  4
2  5  6
3  7  8

In [8]:
data = [{'a': 1, 'b': 2}, {'a': 3, 'b': 4}, {'a': 5, 'b': 6}, {'a': 7, 'b': 8}]
df1 = pd.DataFrame(data, index = ['first', 'second', 'third', 'fourth'], columns = ['a', 'b'])
df1

df2 = pd.DataFrame(data, index = ['first', 'second', 'third', 'fourth'], columns = ['a', 'b1'])

print(df1)
print(df2)

        a  b
first   1  2
second  3  4
third   5  6
fourth  7  8
        a  b1
first   1 NaN
second  3 NaN
third   5 NaN
fourth  7 NaN

In [9]:
dados = {'one': pd.Series([1.,2.,3.], index=['a','b','c']),
         'two': pd.Series([4.,5.,6.], index=['a','b','c'])}
df = pd.DataFrame(dados)
df

   one  two
a  1.0  4.0
b  2.0  5.0
c  3.0  6.0

In [10]:
print("Adicionando uma nova coluna passando com Series:")
df['three'] = pd.Series([10,20,30], index=['a','b','c'])
df

print("Adicionando uma nova coluna usando as colunas existentes no DataFrame:")
df['four'] = df['one'] + df['three']
df

Adicionando uma nova coluna passando com Series:
Adicionando uma nova coluna usando as colunas existentes no DataFrame:

   one  two  three  four
a  1.0  4.0     10  11.0
b  2.0  5.0     20  22.0
c  3.0  6.0     30  33.0

In [15]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d']),
    'three': pd.Series([10,20,30], index=['a','b','c'])}

df = pd.DataFrame(d)
print("O dataframe é:")
print(df)

O dataframe é:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [16]:
print("Excluindo a primeira coluna usando a função DEL:")
del df['one']
print(df)

Excluindo a primeira coluna usando a função DEL:
   two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN

In [17]:
print("Excluindo a primeira linha usando a função POP:")
df.pop('two')
print(df)

Excluindo a primeira linha usando a função POP:
   three
a   10.0
b   20.0
c   30.0
d    NaN

In [18]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}

df = pd.DataFrame(d)
print(df)
print(28*"#")
print(df.loc['b'])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
############################
one    2.0
two    2.0
Name: b, dtype: float64

In [19]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}

df = pd.DataFrame(d)
print(df.iloc[2])

one    3.0
two    3.0
Name: c, dtype: float64

In [20]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}

df = pd.DataFrame(d)
print(df[2:4])

   one  two
c  3.0    3
d  NaN    4

In [27]:
df = pd.DataFrame([[1,2],[3,4]], columns=['a','b'])
df2 = pd.DataFrame([[5,6],[7,8]], columns=['a','b'])

df = df.append(df2)
print(df)

AttributeError: 'DataFrame' object has no attribute 'append'